import Foundation
import SwiftData

@Model
final class PetDNA {
    // User's initial vision in natural language
    var creatureDescription: String
    
    // Parsed DNA traits (generated by Gemini)
    var primaryTheme: String // e.g., "dragon", "robot", "plant", "cosmic"
    var colorPalette: [String] // e.g., ["#FF6B6B", "#4ECDC4"]
    var personality: String // e.g., "playful", "mysterious", "wise"
    var specialTraits: [String] // e.g., ["wings", "horns", "glowing eyes"]
    
    // Evolution preferences (how user interacts)
    var interactionStyle: String // e.g., "frequently fed", "often played with"
    var preferredActivities: [String] // e.g., ["play", "chat"]
    
    // Generation history (for consistency)
    var generationPrompts: [String: String] // stage -> prompt used
    
    init(description: String) {
        self.creatureDescription = description
        self.primaryTheme = ""
        self.colorPalette = []
        self.personality = ""
        self.specialTraits = []
        self.interactionStyle = ""
        self.preferredActivities = []
        self.generationPrompts = [:]
    }
}
